### ISSUE TITLE
error in pypi package: AttributeError: type object 'ClassHolder' has no attribute 'start'

### ISSUE THREAD

**Issue by sirpengi** [jaredly/css#2]
After grabbing codetalker from github and css from pypi:

>  Python 2.7 (r27:82500, Sep 29 2010, 23:01:31) 
>  [GCC 4.5.1 20100924 (Red Hat 4.5.1-4)] on linux2
>  Type "help", "copyright", "credits" or "license" for more information.
> 
>  # from css import css
> 
>  Traceback (most recent call last):
>    File "<stdin>", line 1, in <module>
>    File "/home/sirpengi/virtualenv/zanderloo/lib/python2.7/site-packages/css/**init**.py", line 2, in <module>
>      from grammar import grammar, t as css
>    File "/home/sirpengi/virtualenv/zanderloo/lib/python2.7/site-packages/css/grammar.py", line 64, in <module>
>      @t.translates(ast.start)
>  AttributeError: type object 'ClassHolder' has no attribute 'start'

**Comment by general03** [comment]
Hi,

I've the same error ! Have you resolved it ??

Thank you
